#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dlt-daemon
Version  : 2.18.5
Release  : 9
URL      : https://github.com/GENIVI/dlt-daemon/archive/v2.18.5/dlt-daemon-2.18.5.tar.gz
Source0  : https://github.com/GENIVI/dlt-daemon/archive/v2.18.5/dlt-daemon-2.18.5.tar.gz
Summary  : Diagnostic Log and Trace
Group    : Development/Tools
License  : BSD-3-Clause MIT MPL-2.0
Requires: dlt-daemon-bin = %{version}-%{release}
Requires: dlt-daemon-data = %{version}-%{release}
Requires: dlt-daemon-lib = %{version}-%{release}
Requires: dlt-daemon-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(dbus-1)
BuildRequires : python3
BuildRequires : zlib-dev
Patch1: 0001-dlt_offline-fix-build-failures-with-gcc-10.patch

%description
To build use cmake with -DWITH_DLT_COREDUMPHANDLER=ON -DTARGET_CPU_NAME={i686|x86_64}

%package bin
Summary: bin components for the dlt-daemon package.
Group: Binaries
Requires: dlt-daemon-data = %{version}-%{release}
Requires: dlt-daemon-license = %{version}-%{release}

%description bin
bin components for the dlt-daemon package.


%package data
Summary: data components for the dlt-daemon package.
Group: Data

%description data
data components for the dlt-daemon package.


%package dev
Summary: dev components for the dlt-daemon package.
Group: Development
Requires: dlt-daemon-lib = %{version}-%{release}
Requires: dlt-daemon-bin = %{version}-%{release}
Requires: dlt-daemon-data = %{version}-%{release}
Provides: dlt-daemon-devel = %{version}-%{release}
Requires: dlt-daemon = %{version}-%{release}

%description dev
dev components for the dlt-daemon package.


%package lib
Summary: lib components for the dlt-daemon package.
Group: Libraries
Requires: dlt-daemon-data = %{version}-%{release}
Requires: dlt-daemon-license = %{version}-%{release}

%description lib
lib components for the dlt-daemon package.


%package license
Summary: license components for the dlt-daemon package.
Group: Default

%description license
license components for the dlt-daemon package.


%prep
%setup -q -n dlt-daemon-2.18.5
cd %{_builddir}/dlt-daemon-2.18.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1603684899
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DWITH_DLT_CXX11_EXT=ON
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1603684899
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dlt-daemon
cp %{_builddir}/dlt-daemon-2.18.5/COPYING %{buildroot}/usr/share/package-licenses/dlt-daemon/dfe271856a9bc13ac767a004bae74373048066c5
cp %{_builddir}/dlt-daemon-2.18.5/LICENSE %{buildroot}/usr/share/package-licenses/dlt-daemon/0a5d7250eb460d165c2213af55db0b20c3aa8c35
cp %{_builddir}/dlt-daemon-2.18.5/gtest-1.7.0/LICENSE %{buildroot}/usr/share/package-licenses/dlt-daemon/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/dlt-daemon-2.18.5/src/core_dump_handler/cityhash_c/COPYING %{buildroot}/usr/share/package-licenses/dlt-daemon/345b50630701ae570b0bdcdb186f66408ea8936c
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dlt-control
/usr/bin/dlt-convert
/usr/bin/dlt-daemon
/usr/bin/dlt-example-filetransfer
/usr/bin/dlt-example-user
/usr/bin/dlt-example-user-common-api
/usr/bin/dlt-example-user-func
/usr/bin/dlt-logstorage-ctrl
/usr/bin/dlt-passive-node-ctrl
/usr/bin/dlt-receive
/usr/bin/dlt-sortbytimestamp
/usr/bin/dlt-test-client
/usr/bin/dlt-test-filetransfer
/usr/bin/dlt-test-fork-handler
/usr/bin/dlt-test-init-free
/usr/bin/dlt-test-multi-process
/usr/bin/dlt-test-multi-process-client
/usr/bin/dlt-test-non-verbose
/usr/bin/dlt-test-stress
/usr/bin/dlt-test-stress-client
/usr/bin/dlt-test-stress-user
/usr/bin/dlt-test-user

%files data
%defattr(-,root,root,-)
/usr/share/dlt-filetransfer/dlt-test-filetransfer-file
/usr/share/dlt-filetransfer/dlt-test-filetransfer-image.png

%files dev
%defattr(-,root,root,-)
/usr/include/dlt/dlt.h
/usr/include/dlt/dlt_client.h
/usr/include/dlt/dlt_common.h
/usr/include/dlt/dlt_common_api.h
/usr/include/dlt/dlt_cpp_extension.hpp
/usr/include/dlt/dlt_filetransfer.h
/usr/include/dlt/dlt_offline_trace.h
/usr/include/dlt/dlt_protocol.h
/usr/include/dlt/dlt_shm.h
/usr/include/dlt/dlt_types.h
/usr/include/dlt/dlt_user.h
/usr/include/dlt/dlt_user_macros.h
/usr/include/dlt/dlt_version.h
/usr/lib64/libdlt.so
/usr/lib64/pkgconfig/automotive-dlt-c++.pc
/usr/lib64/pkgconfig/automotive-dlt.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdlt.so.2
/usr/lib64/libdlt.so.2.18.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dlt-daemon/0a5d7250eb460d165c2213af55db0b20c3aa8c35
/usr/share/package-licenses/dlt-daemon/345b50630701ae570b0bdcdb186f66408ea8936c
/usr/share/package-licenses/dlt-daemon/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/dlt-daemon/dfe271856a9bc13ac767a004bae74373048066c5
